local Recipes = {}

Recipes.List = {
	{
		Name = "Omelette", -- Questa è sulla Pan
		Station = "Pan",
		Ingredients = {"Egg", "OliveOil"}
	},
	{
		Name = "CutApple", -- Cambia il nome!
		Station = "KitchenBoard",
		Ingredients = {"Apple", "Apple"}
	},
	{
		Name = "SlicedTomato", -- Cambia il nome!
		Station = "KitchenBoard",
		Ingredients = {"Tomato", "Tomato"}
	},
	{
		Name = "Cookies", -- Cambia il nome!
		Station = "KitchenBoard",
		Ingredients = {"Bread", "Water"}
	},
	{
		Name = "Omelette", -- Cambia il nome!
		Station = "KitchenBoard",
		Ingredients = {"Egg", "Eggplant"}
	},
	{
		Name = "FrenchFries", -- Cambia il nome!
		Station = "KitchenBoard",
		Ingredients = {"Potato"}
	},
	{
		Name = "FrenchFriesCooked", -- Cambia il nome!
		Station = "Fryer",
		Ingredients = {"OliveOil", "FrenchFries"}
	},
	{
		Name = "MilkShakeChocolate", -- Cambia il nome!
		Station = "Mixer",
		Ingredients = {"Chocolate", "Milk"}
	},
	{
		Name = "MilkShakeApple", -- Cambia il nome!
		Station = "Mixer",
		Ingredients = {"Apple", "Milk"}
	},
	{
		Name = "MilkShakeCherry", -- Cambia il nome!
		Station = "Mixer",
		Ingredients = {"Cherry", "Milk"}
	},
	{
		Name = "MilkShakeBanana", -- Cambia il nome!
		Station = "Mixer",
		Ingredients = {"Banana", "Milk"}
	},
	{
		Name = "SpaghettiPomodoro", -- Cambia il nome!
		Station = "Pot",
		Ingredients = {"Pasta", "Tomato","Water","OliveOil"}
	},
	{
		Name = "CookieDough", -- Cambia il nome!
		Station = "Mixer",
		Ingredients = {"Flour", "Chocolate","Sugar","Egg","Milk"}
	},
	{
		Name = "Cookies", -- Cambia il nome!
		Station = "Microwave",
		Ingredients = {"CookieDough"}
	},
	{
		Name = "Salad", -- Cambia il nome!
		Station = "Microwave",
		Ingredients = {"CookieDough"}
	},
	{
		Name = "Burger", -- Cambia il nome!
		Station = "Pot",
		Ingredients = {"Milk"}
	},



}

return Recipes